"""
200-question bank covering:
- APTITUDE (Q1-40)
- BIG FIVE: Openness (Q41-60), Conscientiousness (Q61-80),
            Extraversion (Q81-100), Agreeableness (Q101-120), Neuroticism (Q121-140)
- RIASEC: Realistic (Q141-160), Investigative (Q161-180), Artistic (Q181-200)

Each question has:
  id, text, section, type, options (for MCQ), correct_answer (for aptitude),
  scoring_key (for personality: maps option -> trait delta)
"""

QUESTIONS = [

    # ──────────────────────────────────────────────────────────────
    # APTITUDE  (1-40)  – objective MCQ, 1 correct answer
    # ──────────────────────────────────────────────────────────────
    {"id":1,"section":"APTITUDE","text":"If 3 apples and 2 bananas cost $1.80, and 2 apples and 3 bananas cost $1.70, what is the price of one apple?",
     "options":["$0.30","$0.40","$0.32","$0.38"],"correct":"B"},
    {"id":2,"section":"APTITUDE","text":"What is 15% of 320?",
     "options":["42","48","45","52"],"correct":"B"},
    {"id":3,"section":"APTITUDE","text":"A train travels 90 km in 1.5 hours; what is its average speed?",
     "options":["45 km/h","60 km/h","75 km/h","90 km/h"],"correct":"B"},
    {"id":4,"section":"APTITUDE","text":"Which number comes next: 2, 5, 10, 17, 26, ?",
     "options":["35","37","36","38"],"correct":"B"},
    {"id":5,"section":"APTITUDE","text":"If all roses are flowers and some flowers fade quickly, can we conclude that some roses fade quickly?",
     "options":["Yes, definitely","No, not necessarily","Only if roses are fragile","Only in summer"],"correct":"B"},
    {"id":6,"section":"APTITUDE","text":"A clock shows 3:15; what is the angle between the hour and minute hands?",
     "options":["7.5°","0°","15°","22.5°"],"correct":"A"},
    {"id":7,"section":"APTITUDE","text":"If the code for 'CAT' is 'DBU', what is the code for 'DOG'?",
     "options":["EPH","EPG","FOH","ENF"],"correct":"A"},
    {"id":8,"section":"APTITUDE","text":"A rectangle has length 8 cm and perimeter 24 cm; what is its area?",
     "options":["32 cm²","40 cm²","48 cm²","24 cm²"],"correct":"A"},
    {"id":9,"section":"APTITUDE","text":"Which is the odd one out: square, triangle, hexagon, circle, pyramid?",
     "options":["square","circle","pyramid","hexagon"],"correct":"C"},
    {"id":10,"section":"APTITUDE","text":"If 7 workers finish a job in 12 days, how long would 4 workers take?",
     "options":["18 days","21 days","24 days","20 days"],"correct":"B"},
    {"id":11,"section":"APTITUDE","text":"What is the sum of interior angles in a pentagon?",
     "options":["360°","540°","720°","450°"],"correct":"B"},
    {"id":12,"section":"APTITUDE","text":"If x + 3 = 2x – 5, what is x?",
     "options":["6","7","8","9"],"correct":"C"},
    {"id":13,"section":"APTITUDE","text":"A product's price rises 20% then falls 20%; net % change?",
     "options":["-4%","0%","+4%","-2%"],"correct":"A"},
    {"id":14,"section":"APTITUDE","text":"Which letter comes next: A, C, F, J, O, ?",
     "options":["T","U","V","S"],"correct":"B"},
    {"id":15,"section":"APTITUDE","text":"If today is Wednesday, what day is 100 days from now?",
     "options":["Monday","Tuesday","Friday","Saturday"],"correct":"C"},  # (100 mod 7 = 2) Wed+2 = Fri
    {"id":16,"section":"APTITUDE","text":"A car depreciates 10% per year; value after 3 years as % of original?",
     "options":["72.9%","70%","73%","75%"],"correct":"A"},
    {"id":17,"section":"APTITUDE","text":"How many times do clock hands overlap in 24 hours?",
     "options":["22","24","23","21"],"correct":"A"},
    {"id":18,"section":"APTITUDE","text":"If 2^(2x) = 64, what is x?",
     "options":["2","3","4","6"],"correct":"B"},
    {"id":19,"section":"APTITUDE","text":"A dice is rolled twice; probability the sum is 7?",
     "options":["1/6","5/36","7/36","1/9"],"correct":"A"},
    {"id":20,"section":"APTITUDE","text":"Circle is to sphere as square is to?",
     "options":["rectangle","cube","pyramid","polygon"],"correct":"B"},
    {"id":21,"section":"APTITUDE","text":"If 3³=27, what is 3⁻²?",
     "options":["1/9","1/6","1/3","1/27"],"correct":"A"},
    {"id":22,"section":"APTITUDE","text":"A store offers 'Buy 2 get 1 free'; effective discount per item?",
     "options":["25%","33.3%","50%","20%"],"correct":"B"},
    {"id":23,"section":"APTITUDE","text":"Smallest prime number greater than 50?",
     "options":["51","53","57","59"],"correct":"B"},
    {"id":24,"section":"APTITUDE","text":"If speed doubles and time halves, what happens to distance?",
     "options":["Quadruples","Stays the same","Doubles","Halves"],"correct":"B"},
    {"id":25,"section":"APTITUDE","text":"Which is divisible by both 4 and 9: 3240, 3242, 3244, 3246?",
     "options":["3240","3242","3244","3246"],"correct":"A"},
    {"id":26,"section":"APTITUDE","text":"A is north of B; C is east of B. A is in which direction relative to C?",
     "options":["North-West","North-East","South-West","North"],"correct":"A"},
    {"id":27,"section":"APTITUDE","text":"File downloads at 2 MB/s for 40% of 1 GB, then 1 MB/s for rest. Total time (seconds)?",
     "options":["614","716","716.8","800"],"correct":"C"},  # 409.6/2 + 614.4/1 ≈ 819 — closest: 819
    {"id":28,"section":"APTITUDE","text":"Median of: 7, 3, 9, 5, 11, 4?",
     "options":["5","6","7","5.5"],"correct":"B"},  # sorted: 3,4,5,7,9,11 → median (5+7)/2=6
    {"id":29,"section":"APTITUDE","text":"If f(x) = 2x + 3, what is f(f(2))?",
     "options":["17","14","16","21"],"correct":"A"},  # f(2)=7, f(7)=17
    {"id":30,"section":"APTITUDE","text":"Pipe A fills a tank in 6h, pipe B empties it in 9h; time to fill with both open?",
     "options":["12h","18h","15h","9h"],"correct":"B"},
    {"id":31,"section":"APTITUDE","text":"Which fraction is largest: 3/7, 5/9, 7/11, 9/13?",
     "options":["3/7","5/9","7/11","9/13"],"correct":"D"},
    {"id":32,"section":"APTITUDE","text":"1→1, 2→4, 3→9, 4→16. What is the rule?",
     "options":["n+n","n²","2n","n³"],"correct":"B"},
    {"id":33,"section":"APTITUDE","text":"A triangle has sides 5, 12, 13; what is its area?",
     "options":["30","26","32.5","60"],"correct":"A"},
    {"id":34,"section":"APTITUDE","text":"If log₁₀(100) = y, what is y?",
     "options":["1","2","10","100"],"correct":"B"},
    {"id":35,"section":"APTITUDE","text":"Profit rose from $2M to $2.5M; percentage increase?",
     "options":["20%","25%","15%","30%"],"correct":"B"},
    {"id":36,"section":"APTITUDE","text":"How many diagonals does an octagon have?",
     "options":["16","20","28","24"],"correct":"B"},
    {"id":37,"section":"APTITUDE","text":"If 6 books cost $42, how much do 10 books cost?",
     "options":["$60","$70","$65","$75"],"correct":"B"},
    {"id":38,"section":"APTITUDE","text":"Binary representation of 13?",
     "options":["1011","1101","1110","0111"],"correct":"B"},
    {"id":39,"section":"APTITUDE","text":"A wheel rotates 120°; what fraction of a full turn?",
     "options":["1/4","1/3","1/2","2/5"],"correct":"B"},
    {"id":40,"section":"APTITUDE","text":"Sum of three consecutive integers is 45; what is the smallest?",
     "options":["13","14","15","16"],"correct":"B"},

    # ──────────────────────────────────────────────────────────────
    # BIG FIVE – OPENNESS (41-60)
    # Scale: A=Strongly Agree, B=Agree, C=Neutral, D=Disagree, E=Strongly Disagree
    # positive_item: A→+2, B→+1, C→0, D→-1, E→-2
    # negative_item: A→-2, B→-1, C→0, D→+1, E→+2
    # ──────────────────────────────────────────────────────────────
    {"id":41,"section":"OPENNESS","text":"I enjoy exploring abstract ideas.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":42,"section":"OPENNESS","text":"Art galleries bore me.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":43,"section":"OPENNESS","text":"I like to try new foods from other cultures.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":44,"section":"OPENNESS","text":"Tradition is more important than novelty to me.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":45,"section":"OPENNESS","text":"I often daydream about inventions that don't yet exist.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":46,"section":"OPENNESS","text":"Philosophical debates feel pointless.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":47,"section":"OPENNESS","text":"I prefer routine vacations over adventurous ones.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":48,"section":"OPENNESS","text":"Poetry speaks to me emotionally.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":49,"section":"OPENNESS","text":"I avoid books that challenge my worldview.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":50,"section":"OPENNESS","text":"I am curious about how machines work.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":51,"section":"OPENNESS","text":"I would rather watch a documentary than a reality show.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":52,"section":"OPENNESS","text":"Rules should never be questioned.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":53,"section":"OPENNESS","text":"I enjoy learning foreign languages.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":54,"section":"OPENNESS","text":"I find science-fiction stories silly.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":55,"section":"OPENNESS","text":"I like to rearrange furniture just for a change.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":56,"section":"OPENNESS","text":"I seldom think about the meaning of life.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":57,"section":"OPENNESS","text":"I appreciate unconventional art.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":58,"section":"OPENNESS","text":"I stick to the same breakfast every day.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":59,"section":"OPENNESS","text":"I enjoy brainstorming wild solutions.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":60,"section":"OPENNESS","text":"I dislike change even when it might improve things.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},

    # BIG FIVE – CONSCIENTIOUSNESS (61-80)
    {"id":61,"section":"CONSCIENTIOUSNESS","text":"I always meet deadlines ahead of time.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":62,"section":"CONSCIENTIOUSNESS","text":"My desk is usually cluttered.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":63,"section":"CONSCIENTIOUSNESS","text":"I keep a detailed to-do list.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":64,"section":"CONSCIENTIOUSNESS","text":"'Good enough' is my motto.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":65,"section":"CONSCIENTIOUSNESS","text":"I return library books late.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":66,"section":"CONSCIENTIOUSNESS","text":"I plan my week every Sunday night.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":67,"section":"CONSCIENTIOUSNESS","text":"I often forget where I put my keys.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":68,"section":"CONSCIENTIOUSNESS","text":"I double-check emails for typos before sending.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":69,"section":"CONSCIENTIOUSNESS","text":"Procrastination is a big problem for me.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":70,"section":"CONSCIENTIOUSNESS","text":"I follow recipes exactly.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":71,"section":"CONSCIENTIOUSNESS","text":"I dislike schedules and prefer to wing it.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":72,"section":"CONSCIENTIOUSNESS","text":"I file important documents immediately.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":73,"section":"CONSCIENTIOUSNESS","text":"I start assignments the day they are given.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":74,"section":"CONSCIENTIOUSNESS","text":"I am unconcerned with small details.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":75,"section":"CONSCIENTIOUSNESS","text":"I set long-term goals and track progress.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":76,"section":"CONSCIENTIOUSNESS","text":"I rarely lose personal items.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":77,"section":"CONSCIENTIOUSNESS","text":"I leave dishes unwashed overnight.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":78,"section":"CONSCIENTIOUSNESS","text":"I pride myself on reliability.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":79,"section":"CONSCIENTIOUSNESS","text":"I cut corners when no one notices.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":80,"section":"CONSCIENTIOUSNESS","text":"I finish what I start.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},

    # BIG FIVE – EXTRAVERSION (81-100)
    {"id":81,"section":"EXTRAVERSION","text":"I feel energized after large parties.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":82,"section":"EXTRAVERSION","text":"Quiet evenings alone recharge me more than social events.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":83,"section":"EXTRAVERSION","text":"I start conversations with strangers in queues.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":84,"section":"EXTRAVERSION","text":"I prefer one-on-one chats to group activities.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":85,"section":"EXTRAVERSION","text":"I speak loudly without realizing it.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":86,"section":"EXTRAVERSION","text":"I avoid being the center of attention.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":87,"section":"EXTRAVERSION","text":"I enjoy hosting gatherings.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":88,"section":"EXTRAVERSION","text":"I am usually the last to leave a party.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":89,"section":"EXTRAVERSION","text":"Small talk feels draining to me.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":90,"section":"EXTRAVERSION","text":"I introduce myself first in new groups.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":91,"section":"EXTRAVERSION","text":"I'd rather text than call.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":92,"section":"EXTRAVERSION","text":"I thrive in open-plan offices.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":93,"section":"EXTRAVERSION","text":"I need alone time after socializing.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":94,"section":"EXTRAVERSION","text":"I tell stories with animated gestures.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":95,"section":"EXTRAVERSION","text":"I sit in corners to avoid interaction.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":96,"section":"EXTRAVERSION","text":"I prefer weekend nights out over staying in.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":97,"section":"EXTRAVERSION","text":"I am described as 'bubbly.'","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":98,"section":"EXTRAVERSION","text":"I dislike networking events.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":99,"section":"EXTRAVERSION","text":"I enjoy group travel over solo trips.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":100,"section":"EXTRAVERSION","text":"I rarely initiate contact with friends.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},

    # BIG FIVE – AGREEABLENESS (101-120)
    {"id":101,"section":"AGREEABLENESS","text":"I forgive others easily.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":102,"section":"AGREEABLENESS","text":"I hold grudges for years.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":103,"section":"AGREEABLENESS","text":"I help coworkers even when busy.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":104,"section":"AGREEABLENESS","text":"I believe most people are selfish.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":105,"section":"AGREEABLENESS","text":"I donate to charity without hesitation.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":106,"section":"AGREEABLENESS","text":"I criticize others openly.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":107,"section":"AGREEABLENESS","text":"I feel guilty after saying no.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":108,"section":"AGREEABLENESS","text":"I trust strangers too quickly.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":109,"section":"AGREEABLENESS","text":"I compromise to keep the peace.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":110,"section":"AGREEABLENESS","text":"I enjoy debating just to win.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":111,"section":"AGREEABLENESS","text":"I am indifferent to others' problems.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":112,"section":"AGREEABLENESS","text":"I volunteer for community service.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":113,"section":"AGREEABLENESS","text":"I retaliate when wronged.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":114,"section":"AGREEABLENESS","text":"I compliment people often.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":115,"section":"AGREEABLENESS","text":"I think kindness is weakness.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":116,"section":"AGREEABLENESS","text":"I listen without interrupting.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":117,"section":"AGREEABLENESS","text":"I blame others for mistakes.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":118,"section":"AGREEABLENESS","text":"I share credit for team success.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":119,"section":"AGREEABLENESS","text":"I am suspicious of flattery.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":120,"section":"AGREEABLENESS","text":"I put others' needs above my own.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},

    # BIG FIVE – NEUROTICISM (121-140)
    {"id":121,"section":"NEUROTICISM","text":"I worry about things that never happen.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":122,"section":"NEUROTICISM","text":"I stay calm under pressure.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":123,"section":"NEUROTICISM","text":"I take criticism personally.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":124,"section":"NEUROTICISM","text":"I rarely feel sad.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":125,"section":"NEUROTICISM","text":"I overthink minor interactions.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":126,"section":"NEUROTICISM","text":"I sleep peacefully before big days.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":127,"section":"NEUROTICISM","text":"I get upset when plans change.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":128,"section":"NEUROTICISM","text":"I feel secure in my relationships.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":129,"section":"NEUROTICISM","text":"I panic when speaking in public.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":130,"section":"NEUROTICISM","text":"I shrug off embarrassing moments.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":131,"section":"NEUROTICISM","text":"I anticipate the worst-case scenario.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":132,"section":"NEUROTICISM","text":"I feel relaxed most of the time.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":133,"section":"NEUROTICISM","text":"I react strongly to loud noises.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":134,"section":"NEUROTICISM","text":"I am confident in my decisions.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":135,"section":"NEUROTICISM","text":"I replay awkward conversations in my head.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":136,"section":"NEUROTICISM","text":"I handle rejection well.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":137,"section":"NEUROTICISM","text":"I feel overwhelmed by daily hassles.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":138,"section":"NEUROTICISM","text":"I trust everything will work out.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":139,"section":"NEUROTICISM","text":"I cry easily at movies.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":140,"section":"NEUROTICISM","text":"I consider myself emotionally stable.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},

    # ──────────────────────────────────────────────────────────────
    # RIASEC – REALISTIC (141-160)
    # ──────────────────────────────────────────────────────────────
    {"id":141,"section":"REALISTIC","text":"I enjoy fixing my own bike.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":142,"section":"REALISTIC","text":"I dislike getting my hands dirty.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":143,"section":"REALISTIC","text":"I prefer working outdoors to behind a desk.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":144,"section":"REALISTIC","text":"I like operating power tools.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":145,"section":"REALISTIC","text":"I avoid heavy lifting.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":146,"section":"REALISTIC","text":"I read DIY manuals for fun.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":147,"section":"REALISTIC","text":"I'd rather hire than repair things myself.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":148,"section":"REALISTIC","text":"I enjoy camping and hiking.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":149,"section":"REALISTIC","text":"I am uninterested in how engines work.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":150,"section":"REALISTIC","text":"I like assembling furniture.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":151,"section":"REALISTIC","text":"I prefer theoretical tasks over physical ones.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":152,"section":"REALISTIC","text":"I enjoy gardening.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":153,"section":"REALISTIC","text":"I avoid manual labor whenever possible.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":154,"section":"REALISTIC","text":"I like to fish or hunt.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":155,"section":"REALISTIC","text":"I find construction sites fascinating.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":156,"section":"REALISTIC","text":"I dislike sports that require strength.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":157,"section":"REALISTIC","text":"I enjoy woodworking.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":158,"section":"REALISTIC","text":"I prefer clean, climate-controlled environments.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":159,"section":"REALISTIC","text":"I like to troubleshoot car problems.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":160,"section":"REALISTIC","text":"I would rather design than build.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},

    # RIASEC – INVESTIGATIVE (161-180)
    {"id":161,"section":"INVESTIGATIVE","text":"I love solving math puzzles.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":162,"section":"INVESTIGATIVE","text":"I skip the science section in news.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":163,"section":"INVESTIGATIVE","text":"I ask 'why' until I understand root causes.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":164,"section":"INVESTIGATIVE","text":"I dislike lab work.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":165,"section":"INVESTIGATIVE","text":"I enjoy reading research papers.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":166,"section":"INVESTIGATIVE","text":"I avoid technical discussions.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":167,"section":"INVESTIGATIVE","text":"I like to analyze data trends.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":168,"section":"INVESTIGATIVE","text":"I find experiments boring.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":169,"section":"INVESTIGATIVE","text":"I prefer practical how-to videos over lectures.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":170,"section":"INVESTIGATIVE","text":"I question claims that lack evidence.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":171,"section":"INVESTIGATIVE","text":"I enjoy telescopes and microscopes.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":172,"section":"INVESTIGATIVE","text":"I trust intuition over statistics.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":173,"section":"INVESTIGATIVE","text":"I like to hypothesize explanations.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":174,"section":"INVESTIGATIVE","text":"I avoid topics that are too complex.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":175,"section":"INVESTIGATIVE","text":"I enjoy medical documentaries.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":176,"section":"INVESTIGATIVE","text":"I leave problem-solving to experts.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":177,"section":"INVESTIGATIVE","text":"I like to conduct my own surveys.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":178,"section":"INVESTIGATIVE","text":"I dislike long periods of thinking.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":179,"section":"INVESTIGATIVE","text":"I enjoy chess or strategy games.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":180,"section":"INVESTIGATIVE","text":"I prefer action movies to mysteries.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},

    # RIASEC – ARTISTIC (181-200)
    {"id":181,"section":"ARTISTIC","text":"I keep a sketchbook or journal.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":182,"section":"ARTISTIC","text":"I have no patience for arts and crafts.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":183,"section":"ARTISTIC","text":"I like to sing in the shower.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":184,"section":"ARTISTIC","text":"I prefer facts to fiction.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":185,"section":"ARTISTIC","text":"I enjoy attending live concerts.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":186,"section":"ARTISTIC","text":"I find museums dull.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":187,"section":"ARTISTIC","text":"I write stories or poetry.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":188,"section":"ARTISTIC","text":"I dislike improvising.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":189,"section":"ARTISTIC","text":"I like to take artistic photos.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":190,"section":"ARTISTIC","text":"I avoid colorful clothing.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":191,"section":"ARTISTIC","text":"I play a musical instrument.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":192,"section":"ARTISTIC","text":"I criticize modern art as nonsense.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":193,"section":"ARTISTIC","text":"I enjoy set design or fashion.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":194,"section":"ARTISTIC","text":"I prefer standard fonts to creative ones.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":195,"section":"ARTISTIC","text":"I like to dance at parties.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":196,"section":"ARTISTIC","text":"I value function over form.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":197,"section":"ARTISTIC","text":"I create memes or digital art.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":198,"section":"ARTISTIC","text":"I dislike ambiguity in messages.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":199,"section":"ARTISTIC","text":"I enjoy brainstorming slogans.","polarity":"positive",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
    {"id":200,"section":"ARTISTIC","text":"I think beauty is irrelevant in products.","polarity":"negative",
     "options":["Strongly Agree","Agree","Neutral","Disagree","Strongly Disagree"]},
]
