"""
stage_questions.py
==================
Question banks for Stage 1, 2, 3 adaptive assessments.
Each stage asks ~15-20 targeted questions to discriminate within that level.
All questions are Likert-scale (A=SA, B=A, C=N, D=D, E=SD)
mapped to trait vectors as in scoring.py.
"""

# ─────────────────────────────────────────────────────────────────
# STAGE 1 QUESTIONS — Broad Field Discriminators (~18 questions)
# These distinguish: Science vs Tech vs Arts vs Commerce vs Medicine
# vs Law vs Education vs Trades vs Sports vs Environment
# ─────────────────────────────────────────────────────────────────

STAGE1_QUESTIONS = [
    # Aptitude proxy
    {"id": "S1_01", "text": "I enjoy solving logical or mathematical puzzles.", "polarity": "positive",
     "traits": {"apt": 1.5, "I": 0.5}},
    {"id": "S1_02", "text": "Abstract theoretical problems excite me more than hands-on tasks.", "polarity": "positive",
     "traits": {"I": 1.5, "O": 0.5}},
    {"id": "S1_03", "text": "I prefer creating or making things with my hands.", "polarity": "positive",
     "traits": {"R": 2.0}},
    {"id": "S1_04", "text": "Expressing ideas through art, music, or writing is one of my greatest joys.", "polarity": "positive",
     "traits": {"Art": 2.0}},
    {"id": "S1_05", "text": "I am energised by helping and interacting with other people.", "polarity": "positive",
     "traits": {"A": 1.0, "E": 1.0}},
    {"id": "S1_06", "text": "I am drawn to understanding the human mind and social behavior.", "polarity": "positive",
     "traits": {"I": 1.0, "A": 1.0, "O": 0.5}},
    {"id": "S1_07", "text": "I find myself reading about science news, breakthroughs, or discoveries.", "polarity": "positive",
     "traits": {"I": 1.5, "O": 0.5}},
    {"id": "S1_08", "text": "Numbers and financial data feel natural and interesting to me.", "polarity": "positive",
     "traits": {"apt": 1.5, "C": 0.5}},
    {"id": "S1_09", "text": "I am interested in how computer systems and software work.", "polarity": "positive",
     "traits": {"I": 1.0, "apt": 1.0}},
    {"id": "S1_10", "text": "I would enjoy working outdoors or in physical environments.", "polarity": "positive",
     "traits": {"R": 2.0}},
    {"id": "S1_11", "text": "I feel a strong desire to heal, care for, or improve people's health.", "polarity": "positive",
     "traits": {"A": 1.5, "I": 0.5}},
    {"id": "S1_12", "text": "Teaching and explaining things to others is deeply satisfying.", "polarity": "positive",
     "traits": {"A": 1.0, "E": 1.0}},
    {"id": "S1_13", "text": "Debating ideas, arguing cases, or analysing society appeals to me.", "polarity": "positive",
     "traits": {"E": 1.0, "O": 1.0, "apt": 0.5}},
    {"id": "S1_14", "text": "I care deeply about environmental sustainability and ecological issues.", "polarity": "positive",
     "traits": {"O": 1.0, "A": 0.5, "R": 0.5}},
    {"id": "S1_15", "text": "Physical fitness, sport, or athletic performance interests me greatly.", "polarity": "positive",
     "traits": {"R": 1.5, "E": 0.5}},
    {"id": "S1_16", "text": "I enjoy building or optimising systems and processes.", "polarity": "positive",
     "traits": {"C": 1.0, "I": 1.0}},
    {"id": "S1_17", "text": "I like experimenting, testing hypotheses, and measuring outcomes.", "polarity": "positive",
     "traits": {"I": 1.5, "C": 0.5}},
    {"id": "S1_18", "text": "Creative storytelling, design, or performance speaks to who I am.", "polarity": "positive",
     "traits": {"Art": 2.0}},
]

# ─────────────────────────────────────────────────────────────────
# STAGE 2 QUESTIONS — Sub-Field Discriminators (per field)
# ~15 questions each, dynamically selected based on Stage 1 result
# ─────────────────────────────────────────────────────────────────

STAGE2_QUESTIONS = {

    "Technology": [
        {"id": "T2_01", "text": "Writing code from scratch to solve a problem gives me deep satisfaction.", "polarity": "positive",
         "traits": {"apt": 1.5, "I": 0.5}},
        {"id": "T2_02", "text": "I am fascinated by machine learning, AI, and data patterns.", "polarity": "positive",
         "traits": {"I": 1.5, "apt": 0.5}},
        {"id": "T2_03", "text": "I enjoy designing interfaces that feel intuitive to users.", "polarity": "positive",
         "traits": {"Art": 1.0, "A": 0.5, "E": 0.5}},
        {"id": "T2_04", "text": "Security vulnerabilities and penetration testing intrigue me.", "polarity": "positive",
         "traits": {"I": 1.0, "C": 1.0}},
        {"id": "T2_05", "text": "I enjoy working with hardware, circuits, or physical computing.", "polarity": "positive",
         "traits": {"R": 1.5, "I": 0.5}},
        {"id": "T2_06", "text": "Cloud infrastructure, DevOps pipelines, and automation interest me.", "polarity": "positive",
         "traits": {"C": 1.5, "I": 0.5}},
        {"id": "T2_07", "text": "I think a lot about how products and users interact emotionally.", "polarity": "positive",
         "traits": {"Art": 1.0, "A": 1.0}},
        {"id": "T2_08", "text": "I prefer mathematics and algorithms to aesthetics.", "polarity": "positive",
         "traits": {"apt": 1.5, "I": 0.5}},
        {"id": "T2_09", "text": "I like building things that millions of people will use.", "polarity": "positive",
         "traits": {"E": 1.0, "C": 1.0}},
        {"id": "T2_10", "text": "I think primarily about reliability, uptime, and system performance.", "polarity": "positive",
         "traits": {"C": 1.5, "stab": 0.5}},
        {"id": "T2_11", "text": "Analysing large datasets to find hidden insights excites me.", "polarity": "positive",
         "traits": {"I": 1.5, "apt": 0.5}},
        {"id": "T2_12", "text": "I enjoy creating visual prototypes and wireframes before coding.", "polarity": "positive",
         "traits": {"Art": 1.5, "O": 0.5}},
        {"id": "T2_13", "text": "I find the idea of training neural networks deeply engaging.", "polarity": "positive",
         "traits": {"I": 2.0}},
        {"id": "T2_14", "text": "Network protocols and how the internet works fascinates me.", "polarity": "positive",
         "traits": {"I": 1.0, "C": 1.0}},
        {"id": "T2_15", "text": "I care more about product impact than technical elegance.", "polarity": "positive",
         "traits": {"A": 1.0, "E": 1.0}},
    ],

    "Science": [
        {"id": "SC2_01", "text": "I love conducting experiments and interpreting data.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}},
        {"id": "SC2_02", "text": "I am drawn to the mathematical foundations of physics.", "polarity": "positive",
         "traits": {"apt": 2.0}},
        {"id": "SC2_03", "text": "Living organisms—their structure and function—fascinate me.", "polarity": "positive",
         "traits": {"I": 1.5, "O": 0.5}},
        {"id": "SC2_04", "text": "I find chemical reactions and molecular behavior captivating.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}},
        {"id": "SC2_05", "text": "I am interested in how the human mind and brain work.", "polarity": "positive",
         "traits": {"I": 1.0, "A": 1.0}},
        {"id": "SC2_06", "text": "Coding and computational thinking come naturally to me.", "polarity": "positive",
         "traits": {"apt": 1.5, "I": 0.5}},
        {"id": "SC2_07", "text": "I enjoy fieldwork—collecting samples in nature or the lab.", "polarity": "positive",
         "traits": {"R": 1.5, "O": 0.5}},
        {"id": "SC2_08", "text": "I prefer pure theoretical science over applied science.", "polarity": "positive",
         "traits": {"I": 1.5, "apt": 0.5}},
        {"id": "SC2_09", "text": "I am more excited by biology than physics or chemistry.", "polarity": "positive",
         "traits": {"A": 0.5, "O": 1.0, "I": 0.5}},
        {"id": "SC2_10", "text": "Astronomy, geology, or climate science interests me greatly.", "polarity": "positive",
         "traits": {"O": 1.5, "R": 0.5}},
        {"id": "SC2_11", "text": "I can spend hours reading academic or research papers.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}},
        {"id": "SC2_12", "text": "Statistics and data analysis are core to my thinking.", "polarity": "positive",
         "traits": {"apt": 1.5, "I": 0.5}},
        {"id": "SC2_13", "text": "I want my research to have direct human or societal impact.", "polarity": "positive",
         "traits": {"A": 1.5, "E": 0.5}},
        {"id": "SC2_14", "text": "Understanding genes, DNA, and heredity is especially compelling.", "polarity": "positive",
         "traits": {"I": 2.0}},
        {"id": "SC2_15", "text": "Programming is a tool I naturally reach for in my work.", "polarity": "positive",
         "traits": {"I": 1.0, "apt": 1.0}},
    ],

    "Arts & Humanities": [
        {"id": "A2_01", "text": "I regularly create visual art, illustrations, or design work.", "polarity": "positive",
         "traits": {"Art": 2.0}},
        {"id": "A2_02", "text": "I write stories, essays, or poems for personal expression.", "polarity": "positive",
         "traits": {"Art": 1.0, "O": 1.0}},
        {"id": "A2_03", "text": "Performing—acting, singing, dancing—is where I feel most alive.", "polarity": "positive",
         "traits": {"Art": 1.0, "E": 1.0}},
        {"id": "A2_04", "text": "I am fascinated by history, philosophy, or critical theory.", "polarity": "positive",
         "traits": {"O": 1.5, "I": 0.5}},
        {"id": "A2_05", "text": "Language, translation, and linguistics are deeply interesting to me.", "polarity": "positive",
         "traits": {"O": 1.0, "A": 1.0}},
        {"id": "A2_06", "text": "Film, cinematography, or media production is a passion.", "polarity": "positive",
         "traits": {"Art": 1.5, "O": 0.5}},
        {"id": "A2_07", "text": "I think in images and aesthetics as much as words or logic.", "polarity": "positive",
         "traits": {"Art": 1.5, "O": 0.5}},
        {"id": "A2_08", "text": "I prefer precision and craft over pure spontaneous creativity.", "polarity": "positive",
         "traits": {"C": 1.5, "Art": 0.5}},
        {"id": "A2_09", "text": "Communicating an emotion or idea to an audience drives me.", "polarity": "positive",
         "traits": {"Art": 1.0, "E": 1.0}},
        {"id": "A2_10", "text": "I could spend a day in a library researching cultural history.", "polarity": "positive",
         "traits": {"O": 1.5, "I": 0.5}},
        {"id": "A2_11", "text": "Fashion, interior design, or spatial aesthetics captivate me.", "polarity": "positive",
         "traits": {"Art": 1.5, "O": 0.5}},
        {"id": "A2_12", "text": "I value storytelling as one of humanity's greatest powers.", "polarity": "positive",
         "traits": {"Art": 1.0, "O": 1.0}},
        {"id": "A2_13", "text": "I analyse how language constructs meaning in society.", "polarity": "positive",
         "traits": {"I": 1.0, "O": 1.0}},
        {"id": "A2_14", "text": "I play or have studied a musical instrument seriously.", "polarity": "positive",
         "traits": {"Art": 1.5, "C": 0.5}},
        {"id": "A2_15", "text": "Photographic composition or video editing feels intuitive.", "polarity": "positive",
         "traits": {"Art": 1.5, "R": 0.5}},
    ],

    "Commerce & Business": [
        {"id": "C2_01", "text": "Financial spreadsheets and modelling come easily to me.", "polarity": "positive",
         "traits": {"apt": 1.5, "C": 0.5}},
        {"id": "C2_02", "text": "I enjoy persuading, selling, or pitching ideas to others.", "polarity": "positive",
         "traits": {"E": 1.5, "Art": 0.5}},
        {"id": "C2_03", "text": "I have started or seriously considered starting a business.", "polarity": "positive",
         "traits": {"E": 1.0, "O": 1.0}},
        {"id": "C2_04", "text": "Logistics, supply chains, and operational efficiency fascinate me.", "polarity": "positive",
         "traits": {"C": 1.5, "R": 0.5}},
        {"id": "C2_05", "text": "I care deeply about workplace culture and people management.", "polarity": "positive",
         "traits": {"A": 1.5, "E": 0.5}},
        {"id": "C2_06", "text": "Economic trends and market behavior genuinely interest me.", "polarity": "positive",
         "traits": {"I": 1.5, "apt": 0.5}},
        {"id": "C2_07", "text": "Branding, advertising, and consumer psychology excite me.", "polarity": "positive",
         "traits": {"Art": 1.0, "I": 0.5, "E": 0.5}},
        {"id": "C2_08", "text": "I prefer working with numbers over managing people.", "polarity": "positive",
         "traits": {"apt": 1.5, "I": 0.5}},
        {"id": "C2_09", "text": "Risk, probability, and financial uncertainty intrigue me.", "polarity": "positive",
         "traits": {"apt": 1.5, "stab": 0.5}},
        {"id": "C2_10", "text": "I enjoy leading teams and making strategic decisions.", "polarity": "positive",
         "traits": {"E": 1.5, "C": 0.5}},
        {"id": "C2_11", "text": "Compliance, auditing, and accuracy are important strengths of mine.", "polarity": "positive",
         "traits": {"C": 2.0}},
        {"id": "C2_12", "text": "I find policy, regulation, and economics equally interesting as business.", "polarity": "positive",
         "traits": {"I": 1.0, "O": 1.0}},
        {"id": "C2_13", "text": "I enjoy negotiating, deal-making, and strategic partnerships.", "polarity": "positive",
         "traits": {"E": 1.5, "stab": 0.5}},
        {"id": "C2_14", "text": "I am drawn to fintech, algorithmic trading, or quantitative finance.", "polarity": "positive",
         "traits": {"apt": 1.5, "I": 0.5}},
        {"id": "C2_15", "text": "I think about how to grow revenue and scale a business constantly.", "polarity": "positive",
         "traits": {"E": 1.0, "O": 1.0}},
    ],

    "Medicine & Health": [
        {"id": "M2_01", "text": "I want to diagnose and treat patients directly.", "polarity": "positive",
         "traits": {"I": 1.0, "A": 1.0}},
        {"id": "M2_02", "text": "Precise surgical or procedural skills deeply appeal to me.", "polarity": "positive",
         "traits": {"C": 1.5, "R": 0.5}},
        {"id": "M2_03", "text": "Mental health, therapy, and psychological wellbeing are my focus.", "polarity": "positive",
         "traits": {"A": 1.5, "O": 0.5}},
        {"id": "M2_04", "text": "Laboratory research in drug development or biochemistry interests me.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}},
        {"id": "M2_05", "text": "I prefer supporting patients in recovery rather than diagnosis.", "polarity": "positive",
         "traits": {"A": 1.5, "E": 0.5}},
        {"id": "M2_06", "text": "Public health, epidemiology, and community health policies matter to me.", "polarity": "positive",
         "traits": {"A": 1.0, "I": 1.0}},
        {"id": "M2_07", "text": "I handle high-stress, high-stakes situations with calm.", "polarity": "positive",
         "traits": {"stab": 2.0}},
        {"id": "M2_08", "text": "I am fascinated by the chemistry and pharmacology of drugs.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}},
        {"id": "M2_09", "text": "I connect deeply with patients and their emotional experiences.", "polarity": "positive",
         "traits": {"A": 1.5, "E": 0.5}},
        {"id": "M2_10", "text": "Data, statistics, and population-level health trends excite me.", "polarity": "positive",
         "traits": {"I": 1.5, "apt": 0.5}},
        {"id": "M2_11", "text": "I can see myself doing long residencies and specialising deeply.", "polarity": "positive",
         "traits": {"C": 1.5, "stab": 0.5}},
        {"id": "M2_12", "text": "Understanding how the brain and behavior relate is central to me.", "polarity": "positive",
         "traits": {"I": 1.5, "O": 0.5}},
        {"id": "M2_13", "text": "I value preventative medicine and health education.", "polarity": "positive",
         "traits": {"A": 1.0, "C": 1.0}},
        {"id": "M2_14", "text": "I prefer working with systems and data over individual patients.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}},
        {"id": "M2_15", "text": "Allied health roles like physiotherapy or dietetics appeal to me.", "polarity": "positive",
         "traits": {"R": 1.0, "A": 1.0}},
    ],

    "Law & Social Sciences": [
        {"id": "L2_01", "text": "I enjoy debating and constructing logical arguments.", "polarity": "positive",
         "traits": {"E": 1.0, "apt": 1.0}},
        {"id": "L2_02", "text": "Understanding power structures and political systems drives me.", "polarity": "positive",
         "traits": {"O": 1.5, "I": 0.5}},
        {"id": "L2_03", "text": "I am drawn to advocacy and fighting for justice.", "polarity": "positive",
         "traits": {"A": 1.0, "E": 1.0}},
        {"id": "L2_04", "text": "Human society, culture, and group dynamics fascinate me.", "polarity": "positive",
         "traits": {"O": 1.5, "A": 0.5}},
        {"id": "L2_05", "text": "Criminal behavior, forensics, and investigation intrigue me.", "polarity": "positive",
         "traits": {"I": 1.5, "stab": 0.5}},
        {"id": "L2_06", "text": "I want to directly help vulnerable individuals and communities.", "polarity": "positive",
         "traits": {"A": 2.0}},
        {"id": "L2_07", "text": "I can read and analyse long, complex documents without difficulty.", "polarity": "positive",
         "traits": {"C": 1.5, "apt": 0.5}},
        {"id": "L2_08", "text": "I enjoy fieldwork—interviewing people or collecting social data.", "polarity": "positive",
         "traits": {"E": 1.0, "R": 0.5, "O": 0.5}},
        {"id": "L2_09", "text": "Precision in language and legal terminology matters to me.", "polarity": "positive",
         "traits": {"C": 1.5, "I": 0.5}},
        {"id": "L2_10", "text": "I prefer policy change over direct client work.", "polarity": "positive",
         "traits": {"O": 1.5, "I": 0.5}},
        {"id": "L2_11", "text": "Sociology, social movements, and collective behavior fascinate me.", "polarity": "positive",
         "traits": {"O": 1.0, "A": 1.0}},
        {"id": "L2_12", "text": "I feel energised by courtroom-style arguments and oral advocacy.", "polarity": "positive",
         "traits": {"E": 1.5, "stab": 0.5}},
        {"id": "L2_13", "text": "Crime prevention, policing, and forensic evidence excite me.", "polarity": "positive",
         "traits": {"I": 1.0, "C": 1.0}},
        {"id": "L2_14", "text": "International relations, diplomacy, or geopolitics interests me.", "polarity": "positive",
         "traits": {"O": 1.5, "E": 0.5}},
        {"id": "L2_15", "text": "I want to create systemic change at the institutional level.", "polarity": "positive",
         "traits": {"O": 1.0, "I": 1.0}},
    ],

    "Education": [
        {"id": "E2_01", "text": "Teaching children and watching them grow excites me.", "polarity": "positive",
         "traits": {"A": 1.5, "E": 0.5}},
        {"id": "E2_02", "text": "University-level teaching and academic research appeal to me.", "polarity": "positive",
         "traits": {"I": 1.5, "O": 0.5}},
        {"id": "E2_03", "text": "I love designing courses, curricula, or learning experiences.", "polarity": "positive",
         "traits": {"C": 1.0, "O": 1.0}},
        {"id": "E2_04", "text": "I want to support learners with special educational needs.", "polarity": "positive",
         "traits": {"A": 1.5, "stab": 0.5}},
        {"id": "E2_05", "text": "Corporate training, onboarding, or adult learning energises me.", "polarity": "positive",
         "traits": {"E": 1.5, "C": 0.5}},
        {"id": "E2_06", "text": "I enjoy using technology to enhance learning.", "polarity": "positive",
         "traits": {"I": 1.0, "O": 1.0}},
        {"id": "E2_07", "text": "Classroom management and student discipline are challenges I welcome.", "polarity": "positive",
         "traits": {"stab": 1.5, "C": 0.5}},
        {"id": "E2_08", "text": "I publish or wish to publish research in education journals.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}},
        {"id": "E2_09", "text": "I prefer teaching adults and working professionals.", "polarity": "positive",
         "traits": {"E": 1.0, "C": 1.0}},
        {"id": "E2_10", "text": "Helping disadvantaged students overcome barriers drives me.", "polarity": "positive",
         "traits": {"A": 2.0}},
        {"id": "E2_11", "text": "I think deeply about pedagogy and instructional theory.", "polarity": "positive",
         "traits": {"I": 1.5, "O": 0.5}},
        {"id": "E2_12", "text": "I am drawn to mentoring and advising students one-on-one.", "polarity": "positive",
         "traits": {"A": 1.5, "E": 0.5}},
        {"id": "E2_13", "text": "Building e-learning platforms or educational tools excites me.", "polarity": "positive",
         "traits": {"I": 1.0, "Art": 1.0}},
        {"id": "E2_14", "text": "I want to shape education policy at an institutional level.", "polarity": "positive",
         "traits": {"O": 1.5, "E": 0.5}},
        {"id": "E2_15", "text": "I prefer theoretical research over classroom teaching.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}},
    ],

    "Trades & Engineering": [
        {"id": "TR2_01", "text": "I enjoy working with electrical systems and circuits.", "polarity": "positive",
         "traits": {"R": 1.0, "I": 1.0}},
        {"id": "TR2_02", "text": "Large-scale civil projects—roads, bridges, dams—fascinate me.", "polarity": "positive",
         "traits": {"R": 1.5, "apt": 0.5}},
        {"id": "TR2_03", "text": "The physics of machines and motion deeply interests me.", "polarity": "positive",
         "traits": {"I": 1.5, "R": 0.5}},
        {"id": "TR2_04", "text": "I prefer hands-on construction work to desk-based engineering.", "polarity": "positive",
         "traits": {"R": 2.0}},
        {"id": "TR2_05", "text": "Chemical processes and materials science are core interests.", "polarity": "positive",
         "traits": {"I": 1.5, "apt": 0.5}},
        {"id": "TR2_06", "text": "Vehicles, aeroplanes, or aerospace technology excite me.", "polarity": "positive",
         "traits": {"R": 1.0, "I": 1.0}},
        {"id": "TR2_07", "text": "I enjoy programming microcontrollers and embedded systems.", "polarity": "positive",
         "traits": {"I": 1.0, "R": 1.0}},
        {"id": "TR2_08", "text": "Mathematical modelling and simulation tools are my strength.", "polarity": "positive",
         "traits": {"apt": 1.5, "I": 0.5}},
        {"id": "TR2_09", "text": "Building or repairing structures with my hands is satisfying.", "polarity": "positive",
         "traits": {"R": 2.0}},
        {"id": "TR2_10", "text": "I am attracted to renewable energy and power generation.", "polarity": "positive",
         "traits": {"R": 1.0, "O": 1.0}},
        {"id": "TR2_11", "text": "I enjoy welding, machining, or precision mechanical work.", "polarity": "positive",
         "traits": {"R": 2.0}},
        {"id": "TR2_12", "text": "Structural design and load calculations engage me.", "polarity": "positive",
         "traits": {"apt": 1.5, "I": 0.5}},
        {"id": "TR2_13", "text": "Factory automation and industrial robotics are areas I want to master.", "polarity": "positive",
         "traits": {"I": 1.0, "R": 1.0}},
        {"id": "TR2_14", "text": "I prefer working from detailed technical drawings and specs.", "polarity": "positive",
         "traits": {"C": 1.5, "R": 0.5}},
        {"id": "TR2_15", "text": "Environmental impact of engineering projects matters a lot to me.", "polarity": "positive",
         "traits": {"O": 1.0, "A": 1.0}},
    ],

    "Sports & Physical": [
        {"id": "SP2_01", "text": "Competing and optimising athletic performance drives me.", "polarity": "positive",
         "traits": {"R": 1.5, "stab": 0.5}},
        {"id": "SP2_02", "text": "Coaching methodology and sports science fascinate me.", "polarity": "positive",
         "traits": {"I": 1.0, "A": 1.0}},
        {"id": "SP2_03", "text": "Injury rehabilitation and movement science are my passions.", "polarity": "positive",
         "traits": {"A": 1.0, "I": 1.0}},
        {"id": "SP2_04", "text": "Nutrition and dietary planning for performance interest me.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}},
        {"id": "SP2_05", "text": "Outdoor adventure, leadership, and experiential learning excite me.", "polarity": "positive",
         "traits": {"R": 1.0, "O": 1.0}},
        {"id": "SP2_06", "text": "I love the psychology of sport—motivation, focus, and resilience.", "polarity": "positive",
         "traits": {"I": 1.0, "A": 1.0}},
        {"id": "SP2_07", "text": "The biomechanics of human movement captivates me.", "polarity": "positive",
         "traits": {"I": 1.5, "R": 0.5}},
        {"id": "SP2_08", "text": "I want to work with elite athletes professionally.", "polarity": "positive",
         "traits": {"E": 1.5, "stab": 0.5}},
        {"id": "SP2_09", "text": "Community fitness, public health, and grassroots sport matter.", "polarity": "positive",
         "traits": {"A": 1.5, "E": 0.5}},
        {"id": "SP2_10", "text": "Wearable tech and data analytics in sport interest me.", "polarity": "positive",
         "traits": {"I": 1.5, "O": 0.5}},
        {"id": "SP2_11", "text": "I prefer the analysis side of sport over direct coaching.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}},
        {"id": "SP2_12", "text": "I find physical therapy and patient recovery deeply fulfilling.", "polarity": "positive",
         "traits": {"A": 1.5, "R": 0.5}},
        {"id": "SP2_13", "text": "Youth development and school sport programmes appeal to me.", "polarity": "positive",
         "traits": {"A": 1.5, "E": 0.5}},
        {"id": "SP2_14", "text": "I am passionate about wilderness survival or extreme sports.", "polarity": "positive",
         "traits": {"R": 1.5, "O": 0.5}},
        {"id": "SP2_15", "text": "Sports management, marketing, or events interest me.", "polarity": "positive",
         "traits": {"E": 1.5, "C": 0.5}},
    ],

    "Environment & Agriculture": [
        {"id": "EN2_01", "text": "Atmospheric chemistry and climate modelling fascinate me.", "polarity": "positive",
         "traits": {"I": 1.5, "apt": 0.5}},
        {"id": "EN2_02", "text": "I want to work in crop science, soil health, or agronomy.", "polarity": "positive",
         "traits": {"R": 1.5, "I": 0.5}},
        {"id": "EN2_03", "text": "Wildlife conservation and biodiversity fieldwork excite me.", "polarity": "positive",
         "traits": {"R": 1.0, "O": 1.0}},
        {"id": "EN2_04", "text": "Green energy, carbon capture, and sustainability technology appeal.", "polarity": "positive",
         "traits": {"O": 1.5, "I": 0.5}},
        {"id": "EN2_05", "text": "Marine biology or oceanography is a deep fascination.", "polarity": "positive",
         "traits": {"I": 1.5, "O": 0.5}},
        {"id": "EN2_06", "text": "I care about environmental policy and regulatory frameworks.", "polarity": "positive",
         "traits": {"O": 1.0, "A": 1.0}},
        {"id": "EN2_07", "text": "Water systems, hydrology, and water quality concern me most.", "polarity": "positive",
         "traits": {"I": 1.5, "R": 0.5}},
        {"id": "EN2_08", "text": "Soil science, composting, and regenerative agriculture call to me.", "polarity": "positive",
         "traits": {"R": 1.5, "I": 0.5}},
        {"id": "EN2_09", "text": "I enjoy analysing pollution, contamination, and remediation.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}},
        {"id": "EN2_10", "text": "GIS mapping and spatial data analysis are skills I use or want.", "polarity": "positive",
         "traits": {"I": 1.5, "apt": 0.5}},
        {"id": "EN2_11", "text": "Environmental education and community awareness matter most to me.", "polarity": "positive",
         "traits": {"A": 1.5, "E": 0.5}},
        {"id": "EN2_12", "text": "I prefer laboratory environmental science over fieldwork.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}},
        {"id": "EN2_13", "text": "Forestry, land management, and working in remote areas appeal.", "polarity": "positive",
         "traits": {"R": 1.5, "O": 0.5}},
        {"id": "EN2_14", "text": "Climate justice and environmental equity activism drive me.", "polarity": "positive",
         "traits": {"A": 1.5, "O": 0.5}},
        {"id": "EN2_15", "text": "Food systems, supply chains, and food security fascinate me.", "polarity": "positive",
         "traits": {"I": 1.0, "A": 1.0}},
    ],
}

# ─────────────────────────────────────────────────────────────────
# STAGE 3 QUESTIONS — Specialization Discriminators (~12 questions)
# Generic bank — used for any sub-field not specifically covered.
# Pull from a targeted pool based on sub-field's specializations.
# ─────────────────────────────────────────────────────────────────

STAGE3_QUESTIONS = {

    # Technology specializations
    "Software Development": [
        {"id": "SD3_01", "text": "I love optimising backend performance—databases, caching, latency.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}, "signal": "Backend Engineering"},
        {"id": "SD3_02", "text": "Pixel-perfect UI and smooth user interactions excite me.", "polarity": "positive",
         "traits": {"Art": 1.5, "O": 0.5}, "signal": "Frontend Engineering"},
        {"id": "SD3_03", "text": "Building native mobile apps for iOS or Android is my focus.", "polarity": "positive",
         "traits": {"apt": 1.0, "Art": 1.0}, "signal": "Mobile Development"},
        {"id": "SD3_04", "text": "I want to own the entire stack from browser to database.", "polarity": "positive",
         "traits": {"apt": 1.0, "I": 0.5, "C": 0.5}, "signal": "Full Stack"},
        {"id": "SD3_05", "text": "Low-level programming, kernels, and firmware are fascinating.", "polarity": "positive",
         "traits": {"apt": 1.5, "R": 0.5}, "signal": "Embedded & Systems"},
        {"id": "SD3_06", "text": "Creating interactive games with physics and 3D graphics excites me.", "polarity": "positive",
         "traits": {"Art": 1.0, "I": 1.0}, "signal": "Game Development"},
        {"id": "SD3_07", "text": "I think deeply about API design, contracts, and service boundaries.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}, "signal": "Backend Engineering"},
        {"id": "SD3_08", "text": "Web accessibility, performance budgets, and CSS architecture matter.", "polarity": "positive",
         "traits": {"Art": 1.0, "C": 1.0}, "signal": "Frontend Engineering"},
        {"id": "SD3_09", "text": "Real-time constraints in embedded systems feel like a challenge to solve.", "polarity": "positive",
         "traits": {"I": 1.5, "R": 0.5}, "signal": "Embedded & Systems"},
        {"id": "SD3_10", "text": "I want my software to entertain and emotionally engage people.", "polarity": "positive",
         "traits": {"Art": 1.5, "E": 0.5}, "signal": "Game Development"},
        {"id": "SD3_11", "text": "I enjoy designing the whole product experience end to end.", "polarity": "positive",
         "traits": {"O": 1.0, "C": 1.0}, "signal": "Full Stack"},
        {"id": "SD3_12", "text": "Push notification delivery, battery life, and mobile UX are my concerns.", "polarity": "positive",
         "traits": {"C": 1.0, "Art": 1.0}, "signal": "Mobile Development"},
    ],

    "Artificial Intelligence & Data": [
        {"id": "AI3_01", "text": "Deploying models to production at scale is more important than accuracy.", "polarity": "positive",
         "traits": {"C": 1.5, "I": 0.5}, "signal": "Machine Learning Engineering"},
        {"id": "AI3_02", "text": "I love reading papers on transformer architectures and novel models.", "polarity": "positive",
         "traits": {"I": 1.5, "O": 0.5}, "signal": "Deep Learning & NLP"},
        {"id": "AI3_03", "text": "Statistical hypothesis testing and data storytelling are my strengths.", "polarity": "positive",
         "traits": {"I": 1.0, "C": 1.0}, "signal": "Data Science & Analytics"},
        {"id": "AI3_04", "text": "Building robust ETL pipelines and data warehouses excites me.", "polarity": "positive",
         "traits": {"C": 1.5, "R": 0.5}, "signal": "Data Engineering"},
        {"id": "AI3_05", "text": "Object detection, image segmentation, and video AI fascinate me.", "polarity": "positive",
         "traits": {"I": 1.5, "Art": 0.5}, "signal": "Computer Vision"},
        {"id": "AI3_06", "text": "I want to publish novel AI research and advance the state of the art.", "polarity": "positive",
         "traits": {"I": 1.5, "O": 0.5}, "signal": "AI Research"},
        {"id": "AI3_07", "text": "LLMs, chatbots, and natural language generation are my passion.", "polarity": "positive",
         "traits": {"I": 1.5, "O": 0.5}, "signal": "Deep Learning & NLP"},
        {"id": "AI3_08", "text": "Real-time dashboards, BI reports, and stakeholder communication drive me.", "polarity": "positive",
         "traits": {"E": 1.0, "C": 1.0}, "signal": "Data Science & Analytics"},
        {"id": "AI3_09", "text": "Streaming data pipelines and distributed systems are my focus.", "polarity": "positive",
         "traits": {"I": 1.0, "C": 1.0}, "signal": "Data Engineering"},
        {"id": "AI3_10", "text": "A/B testing, experimentation, and causal inference matter most to me.", "polarity": "positive",
         "traits": {"I": 1.5, "apt": 0.5}, "signal": "Data Science & Analytics"},
        {"id": "AI3_11", "text": "I prefer improving systems reliability and CI/CD for ML over research.", "polarity": "positive",
         "traits": {"C": 1.5, "stab": 0.5}, "signal": "Machine Learning Engineering"},
        {"id": "AI3_12", "text": "3D reconstruction, depth estimation, or medical imaging draws me.", "polarity": "positive",
         "traits": {"I": 1.5, "R": 0.5}, "signal": "Computer Vision"},
    ],

    "Computer Science": [
        {"id": "CS3_01", "text": "I love implementing scalable backend systems and designing APIs.", "polarity": "positive",
         "traits": {"apt": 1.5, "C": 0.5}, "signal": "Software Engineering"},
        {"id": "CS3_02", "text": "Complexity theory, P vs NP, and formal proofs captivate me.", "polarity": "positive",
         "traits": {"apt": 2.0}, "signal": "Theoretical Computer Science"},
        {"id": "CS3_03", "text": "How users mentally model software interaction drives my thinking.", "polarity": "positive",
         "traits": {"A": 1.0, "Art": 1.0}, "signal": "Human-Computer Interaction"},
        {"id": "CS3_04", "text": "Cryptographic protocols and network security are core interests.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}, "signal": "Networks & Security"},
        {"id": "CS3_05", "text": "Query optimisation and storage engines fascinate me.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}, "signal": "Database Systems"},
        {"id": "CS3_06", "text": "Intelligent agents, reinforcement learning, and decision systems.", "polarity": "positive",
         "traits": {"I": 1.5, "apt": 0.5}, "signal": "AI & Machine Learning"},
        {"id": "CS3_07", "text": "Accessibility, inclusive design, and UX research matter most to me.", "polarity": "positive",
         "traits": {"A": 1.5, "Art": 0.5}, "signal": "Human-Computer Interaction"},
        {"id": "CS3_08", "text": "Distributed systems, CAP theorem, and consensus algorithms excite me.", "polarity": "positive",
         "traits": {"I": 1.5, "apt": 0.5}, "signal": "Networks & Security"},
        {"id": "CS3_09", "text": "Software architecture patterns, DDD, and system design dominate my thinking.", "polarity": "positive",
         "traits": {"C": 1.5, "I": 0.5}, "signal": "Software Engineering"},
        {"id": "CS3_10", "text": "Writing clean proofs and mathematical abstractions is satisfying.", "polarity": "positive",
         "traits": {"apt": 2.0}, "signal": "Theoretical Computer Science"},
        {"id": "CS3_11", "text": "OLAP, columnar storage, and big data frameworks are where I thrive.", "polarity": "positive",
         "traits": {"I": 1.0, "C": 1.0}, "signal": "Database Systems"},
        {"id": "CS3_12", "text": "Neural network architectures and backpropagation are intuitive to me.", "polarity": "positive",
         "traits": {"I": 1.5, "apt": 0.5}, "signal": "AI & Machine Learning"},
    ],

    # Generic fallback for any other sub-field
    "_default_": [
        {"id": "GEN3_01", "text": "I prefer deep theoretical understanding over practical application.", "polarity": "positive",
         "traits": {"I": 1.5, "O": 0.5}, "signal": "Research & Theory"},
        {"id": "GEN3_02", "text": "Real-world client impact matters more than academic purity.", "polarity": "positive",
         "traits": {"A": 1.0, "E": 1.0}, "signal": "Applied Practice"},
        {"id": "GEN3_03", "text": "I want to advance the field through original research and publishing.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}, "signal": "Research & Theory"},
        {"id": "GEN3_04", "text": "I prefer direct service delivery and working with people daily.", "polarity": "positive",
         "traits": {"A": 1.5, "E": 0.5}, "signal": "Applied Practice"},
        {"id": "GEN3_05", "text": "Leadership, management, and scaling teams excites me most.", "polarity": "positive",
         "traits": {"E": 1.5, "C": 0.5}, "signal": "Core Track"},
        {"id": "GEN3_06", "text": "I would rather mentor and train others than do individual work.", "polarity": "positive",
         "traits": {"A": 1.5, "E": 0.5}, "signal": "Core Track"},
        {"id": "GEN3_07", "text": "Being the subject-matter expert is more important than managing.", "polarity": "positive",
         "traits": {"I": 1.5, "C": 0.5}, "signal": "Research & Theory"},
        {"id": "GEN3_08", "text": "I love solving concrete problems that clients bring me.", "polarity": "positive",
         "traits": {"A": 1.0, "I": 1.0}, "signal": "Applied Practice"},
        {"id": "GEN3_09", "text": "Creating new systems, frameworks, or methods drives my ambition.", "polarity": "positive",
         "traits": {"O": 1.5, "I": 0.5}, "signal": "Research & Theory"},
        {"id": "GEN3_10", "text": "I am most fulfilled when my work directly changes someone's life.", "polarity": "positive",
         "traits": {"A": 2.0}, "signal": "Applied Practice"},
        {"id": "GEN3_11", "text": "Strategic planning, vision-setting, and direction-giving suit me.", "polarity": "positive",
         "traits": {"E": 1.0, "O": 1.0}, "signal": "Core Track"},
        {"id": "GEN3_12", "text": "I keep detailed records, documentation, and follow processes precisely.", "polarity": "positive",
         "traits": {"C": 1.5, "I": 0.5}, "signal": "Research & Theory"},
    ],
}
